FROM golang:1.25-alpine AS production

WORKDIR /services/api-gateway

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /services/api-gateway/api-gateway main.go

EXPOSE 8080

CMD ["/services/api-gateway/api-gateway"]