name: Create and Push Images to ECR

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - services/**
permissions:
  contents: read
  security-events: write
  pull-requests: write   
  id-token: write  

env: 
  AWS_REGION : "eu-west-2"

jobs:
  DockerImageBuildAndPush:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        service:
          - api-gateway
          - dashboard-api
          - inventory-service
          - notification-service
          - order-service
          - payment-service
          - scheduler
          - shipping-service
          - worker
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
          role-to-assume: ${{ secrets.GitHubActionsRole }}
          role-session-name: GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

    - name: Authenticating docker client to Amazon ECR registry 
      run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }} 

    - name: Building docker image
      run: docker build -t ${{matrix.service}} ./services/${{matrix.service}}

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@v0.36.0
      with:
          image-ref: '${{matrix.service}}'
          format: 'sarif'
          exit-code: 0
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'
 
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
            sarif_file: 'trivy-results.sarif'

    - name: Tagging image to ECR repository
      run: |
        docker tag ${{matrix.service}} ${{ secrets.ECR_REPOSITORY }}/${{matrix.service}}:${{ github.sha }}
        docker tag ${{matrix.service}} ${{ secrets.ECR_REPOSITORY }}/${{matrix.service}}:latest

    - name: Pushing docker image
      run: docker push ${{ secrets.ECR_REPOSITORY }} --all-tags